export const BOOKING_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired',
}

export const ACTIVE_STATUSES = [BOOKING_STATUS.PENDING, BOOKING_STATUS.CONFIRMED]
export const BLOCKING_STATUSES = [BOOKING_STATUS.PENDING, BOOKING_STATUS.CONFIRMED]
export const CANCELLABLE_STATUSES = [BOOKING_STATUS.PENDING]
export const MODIFIABLE_STATUSES = [BOOKING_STATUS.PENDING]
export const PAYABLE_STATUSES = [BOOKING_STATUS.PENDING]
