export const API = {
  health: '/',
  stripeWebhook: '/api/bookings/stripe-webhook',
  auth: {
    base: '/api/auth',
    login: '/api/auth/login',
    register: '/api/auth/register',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
  },
  rooms: {
    base: '/api/rooms',
    owner: '/api/rooms/Owner',
    ownerLower: '/api/rooms/owner',
    trending: '/api/rooms/trending/list',
    toggleAvailability: '/api/rooms/toggle-availability',
    nextNumber: (hotelId) => `/api/rooms/next-number/${hotelId}`,
    byId: (id) => `/api/rooms/${id}`,
  },
  bookings: {
    base: '/api/bookings',
    checkAvailability: '/api/bookings/check-availability',
    calculatePrice: '/api/bookings/calculate-price',
    book: '/api/bookings/book',
    createCheckoutSession: '/api/bookings/create-checkout-session',
    confirmCheckoutSession: '/api/bookings/confirm-checkout-session',
    cancel: '/api/bookings/cancel',
    modify: '/api/bookings/modify',
    pay: '/api/bookings/pay',
    paymentMethod: '/api/bookings/payment-method',
    user: '/api/bookings/user',
    hotel: (hotelId) => `/api/bookings/hotel?hotelId=${hotelId}`,
    ownerDelete: (bookingId) => `/api/bookings/owner/${bookingId}`,
    ownerStatus: (bookingId) => `/api/bookings/owner/${bookingId}/status`,
    ownerUpdatePayment: '/api/bookings/owner/update-payment',
  },
  hotels: {
    base: '/api/hotels',
    owner: '/api/hotels/owner',
    all: '/api/hotels/all',
    search: '/api/hotels/search',
  },
  pricing: {
    base: '/api/pricing',
    suggest: '/api/pricing/suggest',
    occupancy: '/api/pricing/occupancy',
    update: '/api/pricing/update',
    enhanced: '/api/pricing/enhanced',
  },
  guestAssistant: {
    chat: '/api/guest-assistant/chat',
  },
  ai: {
    health: '/api/health',
    chat: '/api/chat/message',
    chatStream: '/api/chat/message/stream',
    conversations: '/api/chat/conversations',
  },
}
